### ISSUE TITLE
Watcher keeps watching even after IDE is closed

### ISSUE THREAD

**Issue by dtgay** [OlivierMary/aw-watcher-jetbrains#102] opened 2022-12-01 02:33 UTC
Not sure if this project is still maintained, but I wanted to file a quick report.

Even after the IDE is closed (RubyMine in my case), the last-viewed file continues to be tracked in AW. The only way I could get it to stop recording the file as being viewed was to uninstall this plugin.

Happy to provide more detail if this project ends up being updated.

**Comment by tmotyl** [comment] 2023-02-02 11:45
sounds like a duplicate of https://github.com/OlivierMary/aw-watcher-jetbrains/issues/61

**Comment by OlivierMary** [comment] 2023-02-02 19:34
Just submit v2.0.0 to JB review when publish can you tell me if changes works for you?

**Closed** 2023-02-04 02:14 UTC
Labels: bug

**Comment by dtgay** [comment] 2023-02-06 00:42
@OlivierMary I've confirmed the bug is fixed. Thank you so much for your work on this watcher!
