### ISSUE TITLE
IntelliJ reports exception

### ISSUE THREAD

**Issue by FlorianKirmaier** [OlivierMary/aw-watcher-jetbrains#4] opened 2019-02-11 14:04 UTC
Thank you for the plugin :)

Here is an exception, which gets reported by IntelliJ:

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:903)
	at java.util.ArrayList$Itr.next(ArrayList.java:853)
	at fr.mary.olivier.aw.watcher.ReportActivity.sendAllEvents(ReportActivity.java:192)
	at fr.mary.olivier.aw.watcher.ReportActivity.lambda$addAndSendEvent$2(ReportActivity.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'm using IntelliJ 2018.3.4 and version 1.0.7 of the plugin.

I don't know how to reproduce this exception, but I hope it's easy to fix with the stacktrace.

I also have the feeling, that after installing the plugin, IntelliJ is more unstable and crashes from time to time. Maybe it's related to this exception?

**Comment by OlivierMary** [comment] 2019-02-11 14:17
Hi @FlorianKirmaier, Thank's for the report !

You use Community Edition or Ultimate ? I use the 2018.3.4 Ultimate And no problem here... With 2-3 IDEA at same time... I will check this, If you can tell me how to reproduce :)

You have this stack every time you change a file in IDEA ? or some times ?

**Comment by FlorianKirmaier** [comment] 2019-02-11 15:24
I'm using the Community Edition.
The exception doesn't happen so often.
I don't know how to reproduce the problem, but I update the ticket when I find out something.

But the slow down of IntelliJ, followed by a crash, happens quite often. It happens more often while selecting files for a commit.

**Comment by OlivierMary** [comment] 2019-02-11 15:26
Hum, do you have the same problem without this plugin ? Maybe a too large project kill your IDEA, can you allocation more xmx to your IDEA ?

**Comment by FlorianKirmaier** [comment] 2019-02-11 15:34
It started to happen after installing the plugin. It happens quite frequently, and before I didn't really notice it. So it's quite save to assume, that it is related to the plugin. 
The JVM already has an unusual big heap of 4gb.

**Comment by OlivierMary** [comment] 2019-02-11 15:57
4Gb In "Help" > "Edit Custom VM Options..." ?

**Comment by FlorianKirmaier** [comment] 2019-02-11 15:58
Yes, to be more precise: `-Xmx3250m`

**Comment by OlivierMary** [comment] 2019-02-11 16:01
Huge ! XD

I had `-Xmx750m` and that never failed ... I open huge project...

**Comment by FlorianKirmaier** [comment] 2019-02-13 13:47
Now the exception happened aggain.
But this time, I've noticed in a second tab another exception.
IntelliJ claims, it happened in the activity-watcher-plugin:

```
java.lang.StackOverflowError
	at java.net.SocketInputStream.read(SocketInputStream.java:178)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
```

**Comment by OlivierMary** [comment] 2019-02-13 15:02
It's a timeout to acces aw-server ... which version of aw-server did you use ? Any application on same port of aw-server ?

**Comment by FlorianKirmaier** [comment] 2019-02-13 16:49
I'm using the version v0.8.0b7.
There is no other process, listening to the same port as aw-server.

**Comment by OlivierMary** [comment] 2019-02-13 19:18
Hum ! The windows incompatible version.... I can't test it :(

**Comment by FlorianKirmaier** [comment] 2019-02-14 11:09
Now, I had the slowdown and the exception at the same time followed with a crash. So it's likely that these two are caused by the same problem. I'm deactivating the plugin for now, because it slows down my productivity.
When there is a new version available, I will test it again.

**Comment by OlivierMary** [comment] 2019-02-14 13:39
I will try when with next version of activity watcher, it's will be release soon I think.

**Comment by dfbag7** [comment] 2019-02-15 13:29
I have got the same `StackOverflowError` exception on PHPStorm with ActivityWatch v.0.8.0b6 on Windows 10:
```
java.lang.StackOverflowError
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
...etc....
```

Other exceptions were listed on the "Induced" tab, but those were the same StackOverflow exceptions:
![default](https://user-images.githubusercontent.com/5889364/52859696-f4c95480-315f-11e9-8360-4e7b826fb484.png)

**Comment by OlivierMary** [comment] 2019-02-15 14:42
Hi @dfbag7 Any idea to reproduce ?

**Comment by dfbag7** [comment] 2019-02-15 15:01
@OlivierMary No exact steps, but I'm suspecting that it can be reproduced when the computer is under heavy load. At that time I had 2 VMs and 2 Idea-based IDEs (GoLand and PHPStorm) running, and also there was a backup application running in background (which produces heavy load to disks causing the whole system to slow down).

**Comment by OlivierMary** [comment] 2019-02-15 15:42
So that can be activity watch very slow ?

**Comment by OlivierMary** [comment] 2019-02-15 15:42
activity watcher server !

**Comment by dfbag7** [comment] 2019-02-15 16:11
yes, that could be

**Comment by Daidalos117** [comment] 2019-02-26 15:11
Same here!
`java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:903)
	at java.util.ArrayList$Itr.next(ArrayList.java:853)
	at fr.mary.olivier.aw.watcher.ReportActivity.sendAllEvents(ReportActivity.java:192)
	at fr.mary.olivier.aw.watcher.ReportActivity.lambda$addAndSendEvent$2(ReportActivity.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

MacOS Mojave, PHPstorm 2018.3 and newest version of plugin/activitywatch...

**Comment by OlivierMary** [comment] 2019-03-11 15:21
Hi there can you tell me if you have the same issue with the last release ?

**Comment by Daidalos117** [comment] 2019-03-21 16:14
It's the same for me. Updated Activitywatch, still getting errors sometimes.

**Comment by luckydonald** [comment] 2019-03-27 14:59
Having exact same exception as OP. Yeah I also seen it going very  s... l... o... w...

**Comment by OlivierMary** [comment] 2019-03-27 16:05
@luckydonald with witch AW server version ?

**Comment by luckydonald** [comment] 2019-03-29 07:46
@OlivierMary Web UI says Version: v0.8.0b7

**Comment by luckydonald** [comment] 2019-04-04 15:07
Yep, IDE is going slow, and also sometimes show an out of memory dialog.

**Comment by OlivierMary** [comment] 2019-04-04 16:15
@luckydonald When I see your logs, it's AW server which lag, and plugin try to resend all activity in one time... will check that

But why AW server lag ? PC on fire ?

**Comment by OlivierMary** [comment] 2019-04-04 17:31
I can reproduce the connexion lost when I stress my HDD. But no failure... Will try stress HDD + CPU + RAM.

**Comment by OlivierMary** [comment] 2019-04-04 18:18
Never fail .. with IDEA 2019.1 Ultimate & AW v0.8.0b8 & aw-watcher-jetbrains v1.0.7

Can you tell me when you have failure on intellij if you have the same with Chrome/FF plugin ? To be sure it's when AW can't absorb requests

**Comment by luckydonald** [comment] 2019-04-07 01:35
I have running the firefox plugin, PHPStorm, Chrome, and IntelliJ.
Like at the same time as I use them all.

**Comment by luckydonald** [comment] 2019-04-07 01:38
In fact, I also often get connection issues in firefox.
Maybe until the real connection problem is somehow fixed could it - to not crash the IDE - drop events buffering like when it reaches a 1 gigabyte?

**Comment by luckydonald** [comment] 2019-04-07 01:43
I believe I have that MacBook (12-inch) from 2017, the one without a cooling fan, so it get's slow sometimes...

**Comment by OlivierMary** [comment] 2019-04-18 09:27
@luckydonald 1gb of events it's very huge... something like 1 years  with 10h usage / hour... without exit IDE.

**Comment by luckydonald** [comment] 2019-04-22 08:33
@OlivierMary as it dies with having 2GB by getting out of memory I'd benefit having it stop growing after 1GB.

Maybe it is somehow sending too many events?
That would explain the AW server getting unresponsive and also why the Firefox plugin disconnects while PHPStorm is running?
How many event's is it supposed to send in which interval?

**Comment by luckydonald** [comment] 2019-04-22 08:37
Were you able to track down the `java.util.ConcurrentModificationException`? Maybe that one fixed could improve things?

**Comment by luckydonald** [comment] 2019-04-22 08:40
> But the slow down of IntelliJ, followed by a crash, happens quite often. It happens more often while selecting files for a commit.
~@FlorianKirmaier [above](#issuecomment-462367574)

I noticed that too.
Could it be related to not having a normal editor up front and therefore getting some invalid state, or something?

**Comment by OlivierMary** [comment] 2019-04-23 08:14
@luckydonald 2GB you talk about IDEA or plugin ? 

I tried stress test on my PC to reproduce and nothing on plugin failure.

If I can't reproduce that's hard to fix it...

If plugin detect timeout when sending events that's stopping synchro while it didn't get an '200' answer form aw-server. After that it send all events in pipe.

If aw-server shutdown while using IDEA it's tested. Maybe I have to try to slow significally aw-server response time to reproduce, but I don't know how (stress test didn't slow it)

**Comment by luckydonald** [comment] 2019-04-24 21:03
Bummer. I don't really have to do anything other than "just wait" :/

**Comment by kw-pr** [comment] 2019-08-07 13:16
I got the same problem. Can't reproduce it but I see it every day.

Server Version: v0.8.dev+c6433ea

```
2019-08-07 14:58:00,725 [21608772]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
2019-08-07 14:58:00,725 [21608772]  ERROR - llij.ide.plugins.PluginManager - OS: Linux
2019-08-07 14:58:00,725 [21608772]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Activity Watcher version: 1.0.7
2019-08-07 14:58:00,725 [21608772]  ERROR - llij.ide.plugins.PluginManager - Last Action: EditorBackSpace
2019-08-07 14:58:00,530 [21608577]  ERROR - llij.ide.plugins.PluginManager - null
java.lang.StackOverflowError
        at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
        at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
        at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
        at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
        at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
        at io.swagger.client.api.DefaultApi$42.intercept(DefaultApi.java:1452)

```

In the raw data I see the same file is transmitted many times. Is that normal?

![grafik](https://user-images.githubusercontent.com/9133572/62625797-40e29e00-b926-11e9-83d4-cba9423d8d81.png)

**Comment by OlivierMary** [comment] 2019-08-16 00:09
I post a new version 1.0.8 tell me if problem is solved. You can DL it from release page on github or wait 2-3d on Jetbrains plugins

**Comment by kw-pr** [comment] 2019-08-21 07:25
Thanks a lot for the update!
Looks fine for me. Bucket show only expected events.
I let you know if it comes up again but I think we can close the issue.

**Comment by OlivierMary** [comment] 2019-08-21 16:53
Thanks @kw-pr

**Comment by OlivierMary** [comment] 2019-10-01 07:07
Hi, there no more errors ? I can close ?

**Comment by kw-pr** [comment] 2019-10-10 07:20
Yes, it is working fine now.
Please close.

Thanks a lot!

**Comment by OlivierMary** [comment] 2019-10-10 12:47
Great

**Closed by OlivierMary** 2019-10-10 12:47 UTC
Labels: bug
