### ISSUE TITLE
Memory and CPU issues

### ISSUE THREAD

**Issue by jdwil** [OlivierMary/aw-watcher-jetbrains#5] opened 2019-06-22 11:49 UTC
This plugin is awesome; thank you. However, I am having some issues with it. It seems to be causing a spike in PyCharm's cpu/memory utilization. The IDE reports it's running out of memory and becomes sluggish so I have to restart it. I just disabled the plugin and have been coding for a while now with no issues.

I'm using:

Debian stretch (LMDE 3)
openjdk version "1.8.0_212"
PyCharm professional edition 2019.1.2

What other info can I give you to help troubleshoot this?

Thanks again!

**Comment by OlivierMary** [comment] 2019-06-24 07:45
Hi there, it's same error than #4 ?

**Comment by jdwil** [comment] 2019-06-24 10:55
@OlivierMary I didn't notice any exception like that, but I need to re-enable the plugin today for some work, so I'll keep an eye out and post again if I see it, or anything else that is new.

**Comment by jdwil** [comment] 2019-06-24 22:48
I just saw this error, but I haven't had any more issues with memory or sluggishness.

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at fr.mary.olivier.aw.watcher.ReportActivity.sendAllEvents(ReportActivity.java:192)
	at fr.mary.olivier.aw.watcher.ReportActivity.lambda$addAndSendEvent$2(ReportActivity.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by OlivierMary** [comment] 2019-06-25 08:05
Any steps to reproduce it ? Nobody can tell me how to reproduce, I tried many stress test while using IDEA and never had this error..

**Comment by jdwil** [comment] 2019-06-28 14:34
Sorry, but I can't seem to reliably reproduce any of the issues. Sometimes I use PyCharm and Webstorm at the same time. Is it possible that that is impacting it?

**Comment by Martomate** [comment] 2019-08-14 20:55
While I don't know the cause of the CPU and memory usage, I do have an idea about why the exception is thrown. Here is a stripped down version of the important code:

```java
public static void addAndSendEvent( ... ) {
    ApplicationManager.getApplication().executeOnPooledThread(() -> {
        Event event = new Event( ... );
        getEventsToSend().add(event);
        sendAllEvents();
    });
}

private static synchronized void sendAllEvents() {
    for (Event event : getEventsToSend()) {
        // send the event
    }
}

private static synchronized List<Event> getEventsToSend() {
    return eventsToSend;
}
```
Imagine the following scenario:
- Thread 1 enters `addAndSendEvents`.
- A new thread is born, call it thread 2. It adds an event to the list and starts running the for loop.
- Thread 1 goes on to do other things.
- After a while thread 1 runs `addAndSendEvents` again.
- A new thread is born, call it thread 3. It adds an event to the list, but since thread 1 is still running the for loop, thread 3 cannot enter `sendAllEvents`. It waits.
- Thread 1 tries to run the next iteration of the for loop, but the list is modified and the exception is thrown.

The fact that ´getEventsToSend´ is synchronized doesn't really do much.

The solution? You can synchronize on the list, like this:
```java
synchronize (eventsToSend) {
    // do things on the list
}

// other code

synchronize (eventsToSend) {
    // do other things on the list
}
```
If a thread is running one of these clauses, the other clause cannot be run and has to wait.

Hope this helps. 

Have a nice day!

**Comment by OlivierMary** [comment] 2019-08-15 19:07
@Martomate thanks will look at this !

**Comment by OlivierMary** [comment] 2019-08-16 00:08
I post a new version 1.0.8 tell me if problem is solved. You can DL it from release page on github or wait 2-3d on Jetbrains plugins

**Comment by Martomate** [comment] 2019-09-30 14:30
It seems to be solved. I haven't seen the error since your fix :)

**Comment by OlivierMary** [comment] 2019-09-30 15:04
Great ! I close it :)

**Closed by OlivierMary** 2019-09-30 15:04 UTC
